package com.prance.lib.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "base_station_table".
*/
public class BaseStationEntityDao extends AbstractDao<BaseStationEntity, Long> {

    public static final String TABLENAME = "base_station_table";

    /**
     * Properties of entity BaseStationEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Sn = new Property(1, String.class, "sn", false, "SN");
    }


    public BaseStationEntityDao(DaoConfig config) {
        super(config);
    }
    
    public BaseStationEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"base_station_table\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"SN\" TEXT NOT NULL UNIQUE );"); // 1: sn
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"base_station_table\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaseStationEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSn());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaseStationEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSn());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BaseStationEntity readEntity(Cursor cursor, int offset) {
        BaseStationEntity entity = new BaseStationEntity( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1) // sn
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaseStationEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSn(cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BaseStationEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BaseStationEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaseStationEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
