package com.prance.lib.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.prance.lib.database.UserEntity;
import com.prance.lib.database.KeyPadEntity;
import com.prance.lib.database.BaseStationEntity;

import com.prance.lib.database.UserEntityDao;
import com.prance.lib.database.KeyPadEntityDao;
import com.prance.lib.database.BaseStationEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig keyPadEntityDaoConfig;
    private final DaoConfig baseStationEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final KeyPadEntityDao keyPadEntityDao;
    private final BaseStationEntityDao baseStationEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        keyPadEntityDaoConfig = daoConfigMap.get(KeyPadEntityDao.class).clone();
        keyPadEntityDaoConfig.initIdentityScope(type);

        baseStationEntityDaoConfig = daoConfigMap.get(BaseStationEntityDao.class).clone();
        baseStationEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        keyPadEntityDao = new KeyPadEntityDao(keyPadEntityDaoConfig, this);
        baseStationEntityDao = new BaseStationEntityDao(baseStationEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(KeyPadEntity.class, keyPadEntityDao);
        registerDao(BaseStationEntity.class, baseStationEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.clearIdentityScope();
        keyPadEntityDaoConfig.clearIdentityScope();
        baseStationEntityDaoConfig.clearIdentityScope();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public KeyPadEntityDao getKeyPadEntityDao() {
        return keyPadEntityDao;
    }

    public BaseStationEntityDao getBaseStationEntityDao() {
        return baseStationEntityDao;
    }

}
