package com.prance.lib.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "keypad_table".
*/
public class KeyPadEntityDao extends AbstractDao<KeyPadEntity, Long> {

    public static final String TABLENAME = "keypad_table";

    /**
     * Properties of entity KeyPadEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property BaseStationId = new Property(1, long.class, "baseStationId", false, "BASE_STATION_ID");
        public final static Property KeyId = new Property(2, String.class, "keyId", false, "KEY_ID");
    }


    public KeyPadEntityDao(DaoConfig config) {
        super(config);
    }
    
    public KeyPadEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"keypad_table\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"BASE_STATION_ID\" INTEGER NOT NULL ," + // 1: baseStationId
                "\"KEY_ID\" TEXT);"); // 2: keyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"keypad_table\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeyPadEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getBaseStationId());
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(3, keyId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeyPadEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getBaseStationId());
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(3, keyId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public KeyPadEntity readEntity(Cursor cursor, int offset) {
        KeyPadEntity entity = new KeyPadEntity( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // baseStationId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // keyId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeyPadEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setBaseStationId(cursor.getLong(offset + 1));
        entity.setKeyId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(KeyPadEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(KeyPadEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KeyPadEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
