package com.prance.lib.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "message_db_table".
*/
public class MessageEntityDao extends AbstractDao<MessageEntity, Long> {

    public static final String TABLENAME = "message_db_table";

    /**
     * Properties of entity MessageEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cmd = new Property(1, int.class, "cmd", false, "CMD");
        public final static Property DataJson = new Property(2, String.class, "dataJson", false, "DATA_JSON");
        public final static Property MsgId = new Property(3, String.class, "msgId", false, "MSG_ID");
    }


    public MessageEntityDao(DaoConfig config) {
        super(config);
    }
    
    public MessageEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"message_db_table\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CMD\" INTEGER NOT NULL ," + // 1: cmd
                "\"DATA_JSON\" TEXT," + // 2: dataJson
                "\"MSG_ID\" TEXT);"); // 3: msgId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_message_db_table_MSG_ID ON \"message_db_table\"" +
                " (\"MSG_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"message_db_table\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MessageEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCmd());
 
        String dataJson = entity.getDataJson();
        if (dataJson != null) {
            stmt.bindString(3, dataJson);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(4, msgId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MessageEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCmd());
 
        String dataJson = entity.getDataJson();
        if (dataJson != null) {
            stmt.bindString(3, dataJson);
        }
 
        String msgId = entity.getMsgId();
        if (msgId != null) {
            stmt.bindString(4, msgId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MessageEntity readEntity(Cursor cursor, int offset) {
        MessageEntity entity = new MessageEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // cmd
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dataJson
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // msgId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MessageEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCmd(cursor.getInt(offset + 1));
        entity.setDataJson(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMsgId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MessageEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MessageEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MessageEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
